# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see http://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod1

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:monospace 8

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
# font pango:DejaVu Sans Mono 8

# Before i3 v4.8, we used to recommend this one as the default:
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
# The font above is very space-efficient, that is, it looks good, sharp and
# clear in small sizes. However, its unicode glyph coverage is limited, the old
# X core fonts rendering does not support right-to-left and this being a bitmap
# font, it doesn’t scale on retina/hidpi displays.

gaps inner 10
gaps outer 0

smart_gaps on

# Notifications
exec --no-startup-id dunst -config ~/.config/dunst/dunstrc

# Backgrounds
exec --no-startup-id feh --bg-fill --randomize ~/Pictures/Desktops/*

for_window [class=".*"] border pixel 3
hide_edge_borders both

# smart_borders on
# client.focused          #4c7899 #285577 #ffffff #2e9ef4   #285577
# client.focused_inactive #333333 #5f676a #ffffff #484e50   #5f676a
# client.unfocused        #333333 #222222 #888888 #292d2e   #222222
# client.urgent           #2f343a #900000 #ffffff #900000   #900000
# client.placeholder      #000000 #0c0c0c #ffffff #000000   #0c0c0c
set $bg-color            #383C4A
set $bd-color            #84927D
set $inactive-bg-color   #383C4A
set $inactive-bd-color   #383C4A
set $text-color          #f3f4f5
set $inactive-text-color #676E7D
#                           border          background      text                 indicator  child border
client.focused              $bd-color       $bg-color       $text-color          #ff0000    $bd-color
# client.unfocused            $bg-color       $bg-color       $inactive-text-color $bg-color  $bg-color
# client.focused_inactive     $bg-color       $bg-color       $inactive-text-color $bg-color  $bg-color
# client.urgent               $bg-color       $bg-color       $text-color          $bg-color  $bg-color
# client.background                           $bg-color



# Color temperature
exec --no-startup-id redshift -l 36:-86 -t 5700:3600
bindsym $mod+Shift+d exec redshift -l 36:-86 -t 5700:3600
bindsym $mod+Shift+f exec pkill -USR1 redshift

# Audio controls
bindsym XF86AudioRaiseVolume exec amixer -c 0 set Speaker 5+
bindsym XF86AudioLowerVolume exec amixer -c 0 set Speaker 5-
bindsym XF86AudioMute exec amixer -c 0 set Master toggle

# Screen brightness controls
# git clone https://github.com/haikarainen/light.git
bindsym XF86MonBrightnessUp exec light -A 5 # increase screen brightness
bindsym XF86MonBrightnessDown exec light -U 5 # decrease screen brightness

# Screenshots and screencapturing!
# bindsym --release Print exec "scrot -s 'screenshot_%Y%m%d_%H%M%S.png' -e 'mv $f ~/Inbox/Screenshots/'"
# bindsym --release Shift+Print exec "scrot -s -e 'screenshot_%Y%m%d_%H%M%S.png' -e 'mv $f ~/Inbox/Screenshots/'"

bindsym --release $mod+p exec "scrot -s 'screenshot_%Y%m%d_%H%M%S.png' -e 'mv $f ~/Inbox/Screenshots/'"
bindsym --release $mod+Shift+p exec "scrot -s -e 'screenshot_%Y%m%d_%H%M%S.png' -e 'mv $f ~/Inbox/Screenshots/'"

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec i3-sensible-terminal

# kill focused window
bindsym $mod+Shift+q kill

# Cycle the monitor DPI and resolutions
bindsym $mod+Shift+s exec --no-startup-id ~/Source/dotfiles/cycle_monitor.sh

# Bind key to toggle off the trackpad
bindsym $mod+Shift+t exec --no-startup-id synclient TouchpadOff=1

# start dmenu (a program launcher)
bindsym $mod+space exec dmenu_run

# There also is the (new) i3-dmenu-desktop which only displays applications
# shipping a .desktop file. It is a wrapper around dmenu, so you need that
# installed.
# bindsym $mod+d exec --no-startup-id i3-dmenu-desktop

# change focus
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+semicolon focus right

# # alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right


# border on, see where focus is
# bindsym $mod+semicolon exec i3-msg border pixel 3
# bindsym --release $mod+semicolon exec i3-msg border pixel 0

# change focus
## bindsym $mod+Left exec i3-msg border pixel 2; focus left
## bindsym $mod+Down exec i3-msg border pixel 2; focus down
## bindsym $mod+Up exec i3-msg border pixel 2; focus up
## bindsym $mod+Right exec i3-msg border pixel 2; focus right
## bindsym --release $mod+Left exec i3-msg border pixel 0
## bindsym --release $mod+Down exec i3-msg border pixel 0
## bindsym --release $mod+Up exec i3-msg border pixel 0
## bindsym --release $mod+Right exec i3-msg border pixel 0
## # alt-tab focus
## bindsym $mod+Tab exec i3-msg border pixel 2; focus right

## # move focused window
## bindsym $mod+Shift+h exec i3-msg border pixel 2; move left
## bindsym $mod+Shift+j exec i3-msg border pixel 2; move down
## bindsym $mod+Shift+k exec i3-msg border pixel 2; move up
## bindsym $mod+Shift+l exec i3-msg border pixel 2; move right
## bindsym --release $mod+Shift+h exec i3-msg border pixel 0
## bindsym --release $mod+Shift+j exec i3-msg border pixel 0
## bindsym --release $mod+Shift+k exec i3-msg border pixel 0
## bindsym --release $mod+Shift+l exec i3-msg border pixel 0



# move focused window
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+semicolon move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
# Coming from OSX I wanted super+space for a launcher
# I'm not sure the purpose of this hotkey anyway
# bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

# switch to workspace
# adding the "number" command allows us to prefix a custom name with a number
# and still be able to jump to it with the number keys
bindsym $mod+1 workspace number 1
bindsym $mod+2 workspace number 2
bindsym $mod+3 workspace number 3
bindsym $mod+4 workspace number 4
bindsym $mod+5 workspace number 5
bindsym $mod+6 workspace number 6
bindsym $mod+7 workspace number 7
bindsym $mod+8 workspace number 8
bindsym $mod+9 workspace number 9
bindsym $mod+0 workspace number 10

# move focused container to workspace
# adding the "number" command allows us to prefix a custom name with a number
# and still be able to jump to it with the number keys
bindsym $mod+Shift+1 move container to workspace number 1
bindsym $mod+Shift+2 move container to workspace number 2
bindsym $mod+Shift+3 move container to workspace number 3
bindsym $mod+Shift+4 move container to workspace number 4
bindsym $mod+Shift+5 move container to workspace number 5
bindsym $mod+Shift+6 move container to workspace number 6
bindsym $mod+Shift+7 move container to workspace number 7
bindsym $mod+Shift+8 move container to workspace number 8
bindsym $mod+Shift+9 move container to workspace number 9
bindsym $mod+Shift+0 move container to workspace number 10

# rename the current workspace
bindsym $mod+Shift+n exec i3-input -F 'rename workspace to "%s"' -P 'Rename workspace: '

# Application and workflow specific hotkeys
#bindsym $mod+t exec i3-input -F 'timew start "%s"' -P 'Track time for: '

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym semicolon resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape
        bindsym Return mode "default"
        bindsym Escape mode "default"
}

bindsym $mod+r mode "resize"

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        status_command i3blocks
}
